### PR TITLE
Update UI of the main page to make it responsive along with other minor CSS fixes

### PR DESCRIPTION
**Pull request by mousamdhakal**
UI of the page updated to be responsive mobile-first

- Mobile view (upto 780px ) full page width single column layout

Screenshot from 2020-10-04 20-17-03

- Tablet view (780px - 1024px) filter column and two column layout

Screenshot from 2020-10-04 20-17-19

- Laptop and desktop view (1024px - 1440px) filter column and four column layout

Screenshot from 2020-10-04 20-17-59

- Large desktop view (1440 + ) filter column and four column layout and extra space at sides 

Screenshot from 2020-10-04 20-18-45

### CODE REVIEW

**Comment by mousamdhakal** [comment]
@jvsinghk  there maybe some other changes seen due to code formatting by prettier than the intended ones.

**Comment by jvsinghk** [comment]
@mousamdhakal great and fast contribution. Is there a way to checkout to your branch and test this on my local? No issue will go through the prettier changes I haven't added that extension while working on Spacex in my VScode.

**Comment by mousamdhakal** [comment]
> @mousamdhakal great and fast contribution. Is there a way to checkout to your branch and test this? No issue will go through the prettier changes I haven't added that extension while working on Spacex in my VScode. 

You can go to the forked repo on my profile, clone that and test locally.

**Comment by jvsinghk** [comment]
> > @mousamdhakal great and fast contribution. Is there a way to checkout to your branch and test this? No issue will go through the prettier changes I haven't added that extension while working on Spacex in my VScode.
> 
> You can go to the forked repo on my profile, clone that, and test locally.

Ohh I thought the same. Asking If there any way other than that. Thank you for your contribution.

**Comment by jvsinghk** [comment]
@mousamdhakal Can you please turn off the prettier and resolve conflicts. Would be easier to review as @jenndroid did.

**Comment by mousamdhakal** [comment]
@jvsinghk  I have reversed the prettier changes as much as possible and fixed merge conflicts, should be no issues now.

**Comment by jvsinghk** [comment]
@mousamdhakal Yes, @jenndroid changed the file name. I changed but at the same, you resolved. So, I reverted back to it. 
The desktop view should have four columns of space information.
Desktop View: The page should have 4 columns between 1024 and 1440 px. Beyond 1440px viewport, the content will be centered align with a max width of 1440.

**Comment by jvsinghk** [comment]
@mousamdhakal Yes, It's resolved. The mobile view should take the full width, tablet view, it should have 2 columns of space information and in the desktop view, the page should have 4 columns of the space information. Including the Filter column, it should be 5 columns in the desktop view. So, we don't have that much space in the bigger screen sizes unused. I have counted the space information columns only not the filter one that might have caused the confusion. Sorry about that. Let me update the issue.

**Comment by mousamdhakal** [comment]
> @mousamdhakal Yes, It's resolved. The mobile view should take the full width, tablet view, it should have 2 columns of space information and in the desktop view, the page should have 4 columns of the space information. Including the Filter column, it should be 5 columns in the desktop view. So, we don't have that much space in the bigger screen sizes unused. I have counted the space information columns only not the filter one that might have caused the confusion. Sorry about that. Let me update the issue.

I will address the full width for the mobile issues, but the number of columns in the breakpoints you are saying is hard to achieve because the cards are larger than the amount of space to accommodate and it will really not look nice to go for forced size for the cards.

**Comment by mousamdhakal** [comment]
@jvsinghk  I have updated layout according to screen sizes as : 

- Mobile view (upto 700px ) full page width single column layout
- Tablet view (700px - 933px) filter column and one column layout
- Tablet and small desktop view (934px - 1241px) filter column and two column layout
- Laptop view (1242px - 1549px) filter column and three column layout
- Desktop view (1550px + ) filter column and four column layout

I have updated the screenshots in PR description as well.

**Comment by jvsinghk** [comment]
> > @mousamdhakal Yes, It's resolved. The mobile view should take the full width, tablet view, it should have 2 columns of space information and in the desktop view, the page should have 4 columns of the space information. Including the Filter column, it should be 5 columns in the desktop view. So, we don't have that much space in the bigger screen sizes unused. I have counted the space information columns only not the filter one that might have caused the confusion. Sorry about that. Let me update the issue.
> 
> I will address the full width for the mobile issues, but the number of columns in the breakpoints you are saying is hard to achieve because the cards are larger than the amount of space to accommodate and it will really not look nice to go for forced size for the cards.

@mousamdhakal - I agree It's hard to achieve maybe we can decrease the size of the card and its content to achieve this. What do you think?
- http://bit.ly/SpacexResponsiveIssue
- Check the above link for issue requirements. I have added the mockups for you.
- Test and Compare the changes with mockups for each view.
- Assign me for review

**Comment by jvsinghk** [comment]
> @jvsinghk I have updated layout according to screen sizes as :
> 
> * Mobile view (upto 700px ) full page width single column layout
> * Tablet view (700px - 933px) filter column and one column layout
> * Tablet and small desktop view (934px - 1241px) filter column and two column layout
> * Laptop view (1242px - 1549px) filter column and three column layout
> * Desktop view (1550px + ) filter column and four column layout
> 
> I have updated the screenshots in PR description as well.

@mousamdhakal 
- Mobile View: The launch details have a margin around the image and its content.
- Tablet View: 3 columns 1 of the filter and the other 2 for launch details information.
- Desktop View: 5 columns 1 for filter and the other 4 for launch details information.
- Desktop View for  Beyond 1440px viewport looks good. It would be great if can have that for between 1024 and 1440 px viewport.

**Comment by mousamdhakal** [comment]
@jvsinghk  I have completed the responsive part as per the requirements and mock-up and updated screenshots on the PR , the inside components do not look too good in some views, I would love to help but I will be busy for the week tomorrow onward,  I would recommend creating another issue for someone else to work on that. Thanks for letting me contribute.

**Comment by jvsinghk** [comment]
@mousamdhakal Thanks for Contributing. You did a great job. I will review it soon and do the rest of the minor fixes. Happy Hacking! Stay Connected!

**Comment by mousamdhakal** [comment]
@jvsinghk  any updates ?

**Comment by jvsinghk** [comment]
@mousamdhakal Please test it.
There are some fixes. I haven't got time to fix them.
- On desktop 
- when we apply any filter like "2007" it displays the launch details on the right side. Although it should display on the left.
- The width of each card must be similar right now the width of the filters card is less and launch details have the same width. 
-The content inside the launch details of `successful launch` and `successful landing` is taking two lines. 

kindly make sure the app behaves it was behaving before as the launch details should start displaying from left after applying filters and increase the width of the space details content as per the filter content in the mobile view.

**Comment by mousamdhakal** [comment]
@jvsinghk Hey, sorry about that, I didn't test applying the filters, I am a little caught up on something, can you create an issue and allow someone to work on top of this to fix those issues, that would be great thanks. :)

**Comment by jvsinghk** [comment]
> @jvsinghk Hey, sorry about that, I didn't test applying the filters, I am a little caught up on something, can you create an issue and allow someone to work on top of this to fix those issues, that would be great thanks. :)

Hey @mousamdhakal Sure, once I get time I will resolve the conflicts and create a new issue.

**Comment by jvsinghk** [comment]
Hey, @mousamdhakal can you create another Pr with changes and fixes as this is not helping the project. Please create a Pr with some other branch name from your master. It's hard to figure out which changes are of your master and which of mine. Fix the merge conflicts by pulling the current master of this repo and add changes to another branch by creating a branch from your fork which is even with this repo's master branch. You can upstream and fetch the master and then checkout to the new branch to do that.

**Comment by jvsinghk** [comment]
Hey, @mousamdhakal kindly create a new PR with fixes and merge conflicts creating a new branch from the master branch of this repo as your branch name is the same as the main branch of this repo. Please create a new branch to add your changes to it. Would be easier to resolve conflicts.

**Comment by mousamdhakal** [comment]
> Hey, @mousamdhakal kindly create a new PR with fixes and merge conflicts creating a new branch from the master branch of this repo as your branch name is the same as the main branch of this repo. Please create a new branch to add your changes to it. Would be easier to resolve conflicts.

I tried to fix the merge conflicts , there are too many changes, and the original changes I have made are completely overwritten and I have a lot of tasks to do as of now and can't manage to work it again, It would be better for you to reopen the issue for someone else. Sorry about this again.

**Comment by jvsinghk** [comment]
> > Hey, @mousamdhakal kindly create a new PR with fixes and merge conflicts creating a new branch from the master branch of this repo as your branch name is the same as the main branch of this repo. Please create a new branch to add your changes to it. Would be easier to resolve conflicts.
> 
> I tried to fix the merge conflicts, there are too many changes, and the original changes I have made are completely overwritten and I have a lot of tasks to do as of now and can't manage to work it again, It would be better for you to reopen the issue for someone else. Sorry about this again.

I am not saying to do this all again as it's not responsive as per requirements as well as not tested for changes with filter and have merge conflicts too. Maybe you can create another PR with the same changes that will resolve merge conflicts at least. No worries, I will see what I can do with it.

**Pull request closed without merging**
